L1=[]
print('L1 is emply now')
print('L1[] is ', L1)
print('Inserting Elements in to the list using append function')
L1.append(10)
L1.append(20)
L1.append(30)
L1.append(40)
L1.append(50)
print('List after insertion')
print(L1)